First commit
FbW36/30-PB-loops-for pull request #1
Opened 2020-10-27 13:46 UTC by AdrianValdes

2020-10-28 13:06 UTC, ciamac-da requested changes
Task2: line 10 if should be(i > 5) because we wanna print until there are 5 bottles!
Task5: print also for for numbers which are multiples of both three and five print "FizzBuzz".
Task 8: !

2020-10-28 13:33 UTC, AdrianValdes commented
Task2: i > 5? What do you mean? Right now it is printing until five. If I put (i > 5) it will not run, or do you mean i < 5; if I put that it would never run with 5. I am lost :(

Task5: Right now it is doing that, check it out :)

2020-10-28 13:44 UTC, ciamac-da commented
Ups my bad task 2 is correct! :))

2020-10-29 14:21 UTC, ciamac-da approved these changes

2020-10-29 14:21 UTC, merged