Tomas' solutions for #30
FbW36/30-PB-loops-for pull request #6
Opened 2020-10-27 16:28 UTC by TomasEliz

2020-10-28 13:58 UTC, ciamac-da requested changes

2020-10-28 13:58 UTC, ciamac-da commented on Tomas/script.js
> +}
Task 7 !

2020-10-29 13:28 UTC, TomasEliz commented
Ok done. But aren't "bonus" assignments voluntary?

On Wed, 28 Oct 2020 at 14:58, cia-from-earth <notifications@github.com>
wrote:

> *@ciamac-da* requested changes on this pull request.
> ------------------------------
>
> In Tomas/script.js
> <https://github.com/FbW36/30-PB-loops-for/pull/6#discussion_r513464436>:
>
> > +  }
> +  else if (i % 3 === 0) {
> +    log(output1);
> +  } else if (i % 5 === 0) {
> +    log(output2);
> +  } else {
> +    log(i);
> +  }
> +}
> +
> +// Write a program to add the multiples of 3 and 5 under 1000
> +for(i = 15; i < 1000; i++) {
> +   if(i % 3 === 0 && i % 5 === 0) {
> +       log(i);
> +   }
> +}
>
> Task 7 !
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FbW36/30-PB-loops-for/pull/6#pullrequestreview-518688625>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQGNSC2RNJ6FHNMRIV325NLSNAPQHANCNFSM4TBCK5NA>
> .
>

2020-10-29 14:25 UTC, ciamac-da approved these changes

2020-10-29 14:25 UTC, merged